env:
  browser: true
  commonjs: true
plugins:
  - node
  - prettier
extends:
  - 'eslint:recommended'
  - prettier
parserOptions:
  ecmaVersion: 5
globals:
  cc: true
  sp: true
  jsb: true
  CryptoJS: true
  dmm: false
  opensocial: false
  gadgets: false
  $: false

rules:
  # Core rules
  array-callback-return: error
  arrow-body-style:
    - error
    - "as-needed"
  arrow-spacing: error
  block-scoped-var: off
  callback-return:
    - error
    -
      - callback
      - cb
      - next
      - done
  camelcase:
    - error
    -
      properties: never
  complexity:
    - error
    - 10
  constructor-super: error
  curly:
    - error
    - all
  eqeqeq: error
  for-direction: error
  func-style:
    - error
    - declaration
    -
      allowArrowFunctions: true
  global-require: error
  handle-callback-err: error
  linebreak-style:
    - error
    - unix
  max-depth:
    - error
    - 5
  max-lines:
    - error
    - 800
  max-nested-callbacks:
    - error
    - 3
  max-params:
    - error
    - 10
  max-statements:
    - error
    - 30
  max-statements-per-line:
    - error
    -
      max: 2
  object-shorthand:
    - error
    - never
  one-var:
    - error
    - never
  prefer-arrow-callback: off
  prefer-const: error
  prefer-numeric-literals: error
  prefer-rest-params: off
  radix: off
  require-yield: error
  spaced-comment:
    - error
    - always
    -
      exceptions:
        - "-"
        - "+"
        - "*"
      block:
        balanced: true
  strict: error
  use-isnan: error
  valid-typeof: error
  wrap-iife: error

  # Forbidden patterns
  no-alert: error
  no-array-constructor: error
  no-bitwise: off
  no-caller: error
  no-case-declarations: error
  no-catch-shadow: error
  no-class-assign: error
  no-cond-assign: error
  no-console:
    - error
    -
      allow:
      - "warn"
      - "error"
  no-const-assign: error
  no-constant-condition: error
  no-continue: error
  no-control-regex: error
  no-debugger: error
  no-delete-var: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-empty: error
  no-empty-character-class: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: off
  no-ex-assign: error
  no-extend-native: off
  no-extra-bind: error
  no-extra-boolean-cast: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-func-assign: error
  no-global-assign: error
  no-implied-eval: error
  no-inline-comments: off
  no-inner-declarations: error
  no-invalid-regexp: error
  no-invalid-this: off
  no-irregular-whitespace: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-mixed-requires: error
  no-mixed-spaces-and-tabs:
    - error
    - false
  no-multi-str: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-symbol: error
  no-new-wrappers: error
  no-obj-calls: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: off
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-redeclare: warn
  no-regex-spaces: error
  no-restricted-syntax:
    - error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-sparse-arrays: error
  no-sync: error
  no-this-before-super: error
  no-throw-literal: error
  no-undef: error
  no-undef-init: error
  no-unexpected-multiline: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-labels: error
  no-unused-vars:
    - off
    - args: none
  no-use-before-define: off
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-concat: error
  no-useless-rename: error
  no-void: error
  no-warning-comments:
    - error
    -
      terms:
        - "----"
        - "XXX"
  no-with: error

  # Node rules
  node/exports-style:
    - error
  node/no-deprecated-api: error
  node/no-extraneous-import: error
  node/no-extraneous-require: error

  # Formatting
  prettier/prettier:
    - error
    -
      singleQuote: true
      useTabs: true
      printWidth: 120
